Repository facebookresearch/BenchMARL, pull requests merged in 2024-07, with the labels that each got.

#108 [Feature] Run evaluation on first iteration
  .github/unittest/install_vmas.sh
  benchmarl/experiment/experiment.py
Labels: enhancement, CLA Signed

#105 [Docs] WandB Sweeps example with BenchMARL
  examples/sweep/wandb/readme.md
  examples/sweep/wandb/sweepconfig.yaml
Labels: documentation, CLA Signed

#109 [CI] Fix SMACv2
  .github/workflows/smacv2_tests.yml
  test/test_smacv2.py
Labels: CLA Signed, smacv2

#114 [BugFix] Fix collect with grad
  benchmarl/conf/experiment/base_experiment.yaml
  benchmarl/experiment/experiment.py
  test/test_vmas.py
Labels: CLA Signed
